import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'server/**/*.test.ts',
      'api/**/*.test.ts',
    ],
    coverage: {
      provider: 'v8',
      all: true,
      reporter: ['text', 'json-summary', 'html'],
      include: [
        'api/report-share.ts',
        'api/telegram-webhook.ts',
        'server/lib/sendApi/**/*.ts',
        'server/lib/telegramWebhook/commands.ts',
        'server/lib/telegramWebhook/rbac.ts',
        'server/lib/telegramWebhook/tags.ts',
        'server/lib/telegramWebhook/uploadFlow.ts',
        'src/lib/mappers.ts',
        'src/lib/sanitize.ts',
        'src/lib/emailCore.ts',
        'src/lib/visualLedAssist.ts',
        'src/lib/visualLed/**/*.ts',
        'src/lib/content/homeEquipmentSection.ts',
        'src/lib/content/homeEquipmentSectionHeader.ts',
        'src/lib/i18n/adminSourceLabel.ts',
        'src/hooks/useCases.ts',
        'src/hooks/useEditableBinding.tsx',
        'src/hooks/useFormDraftPersistence.ts',
        'src/hooks/useUserRole.ts',
        'src/components/visualLed/demoVideos.ts',
        'src/components/visualLed/loadProject.ts',
        'src/components/visualLed/saveProject.ts',
        'src/components/visualLed/state/history.ts',
        'src/components/visualLed/state/persistence.ts',
        'src/components/visualLed/state/reducer.ts',
      ],
      exclude: [
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',
        'src/lib/supabase.types.ts',
      ],
      thresholds: {
        lines: 70,
        statements: 70,
        functions: 70,
        branches: 60,
      },
    },
  },
});
