export const adminCasesRedesignedContent = {
  validation: {
    slugRequired: 'Slug обязателен',
    slugPattern: 'Slug: только латиница, цифры и дефис',
    titleRequired: 'Название обязательно',
    summaryRequired: 'Описание обязательно',
  },
  formatOptions: [
    'Корпоратив',
    'Концерт',
    'Конференция',
    'Выставка',
    'Свадьба',
    'Презентация',
    'Фестиваль',
    'Тимбилдинг',
    'Другое',
  ],
  layout: {
    title: 'Кейсы',
    subtitle: 'Управление проектами и медиа-библиотека',
  },
  tabs: {
    cases: 'Кейсы',
    media: 'Медиа-библиотека',
  },
  toasts: {
    saveError: 'Ошибка сохранения кейса',
    updateSuccess: 'Кейс обновлен',
    addSuccess: 'Кейс добавлен',
    deleteSuccess: 'Кейс удален',
    deleteError: 'Не удалось удалить кейс',
    resetSuccess: 'Кейсы сброшены к демо-значениям',
  },
  confirm: {
    deleteTitle: 'Удалить кейс?',
    deleteDescription: (title: string) => `Кейс "${title}" будет удален без возможности восстановления.`,
    deleteConfirm: 'Удалить',
    cancel: 'Отмена',
    resetTitle: 'Сбросить все кейсы к дефолту?',
    resetDescription: 'Текущие кейсы будут перезаписаны демо-значениями.',
    resetConfirm: 'Сбросить',
  },
  mediaSection: {
    title: 'Медиа-библиотека',
    description: 'Централизованное хранилище фото и видео с тегами',
  },
  form: {
    editTitle: 'Редактирование кейса',
    newTitle: 'Новый кейс',
    unsavedChanges: 'Есть несохраненные изменения',
    cancel: 'Отмена',
    slugLabel: 'Slug*',
    slugAutoLabel: '(авто)',
    slugPlaceholder: 'nazvanie-kejsa',
    slugHint: 'Уникальный идентификатор для URL',
    titleLabel: 'Название*',
    titlePlaceholder: 'Например: Корпоратив Газпром',
    cityLabel: 'Город',
    cityPlaceholder: 'Екатеринбург',
    dateLabel: 'Дата',
    formatLabel: 'Формат',
    formatPlaceholder: 'Выберите формат',
    summaryLabel: 'Краткое описание*',
    summaryPlaceholder: 'Описание задачи и что было сделано...',
    metricsLabel: 'Метрики',
    metricsPlaceholder: '500+ гостей, 50 м² экран',
    servicesLabel: 'Услуги (через запятую)',
    servicesPlaceholder: 'LED-экран, звук, свет',
    mediaFilesLabel: 'Медиафайлы',
    submitting: 'Сохраняем...',
    submitEdit: 'Сохранить изменения',
    submitCreate: 'Добавить кейс',
  },
  list: {
    title: 'Список кейсов',
    resetAction: 'Сброс к дефолту',
    searchPlaceholder: 'Поиск по названию, городу, формату...',
    separator: '•',
    photosSuffix: 'фото',
    videosSuffix: 'видео',
    editAction: 'Ред.',
    deleteAction: 'Удалить',
    emptyTitle: 'Кейсов пока нет',
    emptySearchDescription: 'По вашему запросу ничего не найдено',
    emptyDefaultDescription: 'Добавьте первый кейс через форму слева',
  },
} as const;
