export const adminCategoriesPageContent = {
  validation: {
    idPositive: 'ID должен быть числом',
    titleRequired: 'Название обязательно',
    shortDescriptionRequired: 'Добавьте краткое описание',
    bulletsRequired: 'Добавьте преимущества',
    pagePathRequired: 'Путь обязателен',
    pagePathPrefix: 'Путь должен начинаться с /',
  },
  toast: {
    saveError: 'Ошибка сохранения категории',
    created: 'Категория добавлена',
    updated: 'Категория обновлена',
    deleted: 'Категория удалена',
    deleteError: 'Ошибка удаления категории',
    resetSuccess: 'Категории сброшены к дефолту',
  },
  layout: {
    title: 'Категории',
    subtitle: 'Управление категориями аренды',
  },
  deleteModal: {
    title: 'Удалить категорию?',
    confirmText: 'Удалить',
    cancelText: 'Отмена',
    description: (title: string) => `Категория "${title}" будет удалена без возможности восстановления.`,
  },
  resetModal: {
    title: 'Сбросить категории к дефолту?',
    description: 'Текущий список категорий будет перезаписан демо-данными.',
    confirmText: 'Сбросить',
    cancelText: 'Отмена',
  },
  form: {
    editTitle: 'Редактирование категории',
    createTitle: 'Новая категория',
    editDescription: (id: number) =>
      `Вы редактируете категорию ${String(id)}. Сохраните изменения или нажмите «Отмена».`,
    createDescription: 'Создайте новую категорию или выберите существующую справа для редактирования.',
    restoredDraft: 'Восстановлен черновик формы, можно продолжить с того же места.',
    editMode: 'Режим редактирования',
    unsavedChanges: 'Есть несохраненные изменения',
    cancel: 'Отмена',
    idLabel: 'ID',
    titleLabel: 'Название',
    shortDescriptionLabel: 'Краткое описание',
    bulletsLabel: 'Буллеты',
    bulletsHint: 'Каждый пункт с новой строки',
    pagePathLabel: 'Путь страницы',
    save: 'Сохранить',
    add: 'Добавить',
  },
  list: {
    title: 'Список категорий',
    shown: (filteredCount: number, totalCount: number) => `Показано ${filteredCount} из ${totalCount}`,
    resetToDefault: 'Сброс к дефолту',
    searchPlaceholder: 'Поиск по названию, пути, описанию...',
    clear: 'Очистить',
    pagePathPrefix: 'Путь:',
    edit: 'Редактировать',
    remove: 'Удалить',
    emptyTitle: 'Категорий пока нет',
    notFoundTitle: 'Ничего не найдено',
    emptyDescription: 'Создайте первую категорию аренды через форму слева.',
    notFoundDescription: 'Попробуйте изменить поисковый запрос или очистить фильтр.',
  },
} as const;
