import type { Locale } from '../../i18n/types';
import type { JsonDiffEntry } from '../../lib/jsonDiff';

const ru = {
  title: 'История изменений контента',
  subtitle: 'Audit-trail правок site_content. Для UPDATE кнопка откатывает выбранную правку к предыдущему снимку, восстановление создаёт новую запись истории.',
  filterLabel: 'Ключ',
  allKeys: 'Все ключи',
  refresh: 'Обновить',
  cancel: 'Отмена',
  restoreConfirm: 'Восстановить эту версию? Текущий контент будет перезаписан (новая запись в истории).',
  rollbackConfirm: 'Откатить эту правку? Текущий контент будет заменён состоянием до выбранного изменения.',
  restoring: 'Восстанавливаю…',
  restoreSuccess: 'Восстановлено',
  restoreError: 'Не удалось восстановить',
  previewLoadError: 'Не удалось загрузить текущий контент для предпросмотра',
  diffLoadError: 'Не удалось загрузить снимки для диффа',
  previousVersionMissing: 'Не найден предыдущий снимок для отката этой правки',
  showDiff: 'Показать дифф',
  diffTitle: 'Дифф изменения',
  diffIntro: 'Просмотр того, что изменилось в этой записи истории. Здесь ничего не восстанавливается.',
  diffBefore: 'До изменения',
  diffAfter: 'После изменения',
  diffClose: 'Закрыть',
  diffNoChanges: 'В этой записи не найдено отличий по сохраняемым полям.',
  diffChangedCount: (n: number) => `Изменено полей: ${n}`,
  diffJsonBadge: 'JSON-дифф',
  diffJsonPathsCount: (n: number) => `Путей изменилось: ${n}`,
  diffJsonHeaders: { path: 'Путь', before: 'До', after: 'После', root: '(корень)' },
  diffJsonKinds: { added: 'добавлено', removed: 'удалено', changed: 'изменено' } as Record<JsonDiffEntry['kind'], string>,
  previewRestoreTitle: 'Предпросмотр восстановления',
  previewRollbackTitle: 'Предпросмотр отката правки',
  previewRestoreIntro: 'Сравнение показывает, какие поля текущей записи будут заменены значениями из выбранной версии.',
  previewRollbackIntro: 'Сравнение показывает, какие поля вернутся к состоянию до выбранного изменения.',
  previewLoading: 'Загружаю текущую версию…',
  previewCurrent: 'Сейчас',
  previewRestored: 'Станет после восстановления',
  previewChanged: 'Изменится',
  previewClose: 'Закрыть предпросмотр',
  previewNoCurrent: 'Текущая запись не найдена. Восстановление создаст запись из выбранного снепшота.',
  previewNoChanges: 'Целевой снимок совпадает с текущим контентом. Новая запись истории будет без визуальных изменений.',
  previewChangedCount: (n: number) => `Изменится полей: ${n}`,
  rowActions: {
    INSERT: 'Восстановить',
    UPDATE: 'Откатить',
    DELETE: 'Восстановить',
  },
  primaryActions: {
    INSERT: 'Восстановить',
    UPDATE: 'Откатить правку',
    DELETE: 'Восстановить',
  },
  loadError: 'Не удалось загрузить историю',
  noVersions: 'Правок пока нет',
  fieldLabels: {
    title: 'Заголовок RU',
    content: 'Текст RU',
    contentHtml: 'HTML RU',
    metaTitle: 'Meta title RU',
    metaDescription: 'Meta description RU',
    fontSize: 'Размер шрифта RU',
    titleEn: 'Заголовок EN',
    contentEn: 'Текст EN',
    contentHtmlEn: 'HTML EN',
    metaTitleEn: 'Meta title EN',
    metaDescriptionEn: 'Meta description EN',
    fontSizeEn: 'Размер шрифта EN',
    isPublished: 'Опубликовано',
  },
  columns: {
    when: 'Когда',
    key: 'Ключ',
    op: 'Операция',
    editor: 'Кем',
    summary: 'Содержимое',
    actions: '',
  },
  operationLabels: {
    INSERT: 'Создано',
    UPDATE: 'Изменено',
    DELETE: 'Удалено',
  },
  keyStats: (n: number) => `${n} ключей с правками`,
  searchLabel: 'Поиск',
  searchPlaceholder: 'Ключ, текст, поле…',
  searchClear: 'Очистить поиск',
  opFilterHint: 'Фильтр по операции',
  emptyAfterFilter: 'Под фильтр ничего не попало. Попробуйте сбросить поиск или операции.',
  showingFiltered: (visible: number, total: number) =>
    visible === total ? `${total} записей` : `${visible} из ${total} записей`,
  loadMore: 'Показать ещё',
  loadingMore: 'Загружаю…',
  endOfHistory: 'Это все записи',
  compareCheckbox: 'Выбрать для сравнения',
  compareShort: 'Сравнить',
  compareSelected: (n: number) => `Выбрано: ${n}/2`,
  compareDifferentKeys: 'Можно сравнивать только версии одного ключа',
  compareAction: 'Сравнить выбранные',
  compareReset: 'Сбросить выбор',
};

const en: typeof ru = {
  title: 'Content change history',
  subtitle: 'site_content audit trail. UPDATE rows can be undone to the previous snapshot; restore writes a new history entry.',
  filterLabel: 'Key',
  allKeys: 'All keys',
  refresh: 'Refresh',
  cancel: 'Cancel',
  restoreConfirm: 'Restore this version? Current content will be overwritten (new history entry).',
  rollbackConfirm: 'Undo this edit? Current content will be replaced with the state before the selected change.',
  restoring: 'Restoring…',
  restoreSuccess: 'Restored',
  restoreError: 'Restore failed',
  previewLoadError: 'Failed to load current content for preview',
  diffLoadError: 'Failed to load snapshots for diff',
  previousVersionMissing: 'Previous snapshot for this edit was not found',
  showDiff: 'Show diff',
  diffTitle: 'Change diff',
  diffIntro: 'Read-only view of what changed in this history entry. Nothing is restored here.',
  diffBefore: 'Before change',
  diffAfter: 'After change',
  diffClose: 'Close',
  diffNoChanges: 'No differences were found in saved fields for this entry.',
  diffChangedCount: (n: number) => `${n} fields changed`,
  diffJsonBadge: 'JSON diff',
  diffJsonPathsCount: (n: number) => `${n} paths changed`,
  diffJsonHeaders: { path: 'Path', before: 'Before', after: 'After', root: '(root)' },
  diffJsonKinds: { added: 'added', removed: 'removed', changed: 'changed' } as Record<JsonDiffEntry['kind'], string>,
  previewRestoreTitle: 'Restore preview',
  previewRollbackTitle: 'Undo edit preview',
  previewRestoreIntro: 'The comparison shows which fields of the current record will be replaced by the selected snapshot.',
  previewRollbackIntro: 'The comparison shows which fields will return to the state before the selected edit.',
  previewLoading: 'Loading current version…',
  previewCurrent: 'Current',
  previewRestored: 'After restore',
  previewChanged: 'Will change',
  previewClose: 'Close preview',
  previewNoCurrent: 'Current record was not found. Restore will create the record from this snapshot.',
  previewNoChanges: 'The target snapshot matches current content. Restore will create a new history entry without visible changes.',
  previewChangedCount: (n: number) => `${n} fields will change`,
  rowActions: {
    INSERT: 'Restore',
    UPDATE: 'Undo',
    DELETE: 'Restore',
  },
  primaryActions: {
    INSERT: 'Restore',
    UPDATE: 'Undo edit',
    DELETE: 'Restore',
  },
  loadError: 'Failed to load history',
  noVersions: 'No edits yet',
  fieldLabels: {
    title: 'Title RU',
    content: 'Content RU',
    contentHtml: 'HTML RU',
    metaTitle: 'Meta title RU',
    metaDescription: 'Meta description RU',
    fontSize: 'Font size RU',
    titleEn: 'Title EN',
    contentEn: 'Content EN',
    contentHtmlEn: 'HTML EN',
    metaTitleEn: 'Meta title EN',
    metaDescriptionEn: 'Meta description EN',
    fontSizeEn: 'Font size EN',
    isPublished: 'Published',
  },
  columns: {
    when: 'When',
    key: 'Key',
    op: 'Operation',
    editor: 'By',
    summary: 'Content',
    actions: '',
  },
  operationLabels: {
    INSERT: 'Created',
    UPDATE: 'Updated',
    DELETE: 'Deleted',
  },
  keyStats: (n: number) => `${n} keys with edits`,
  searchLabel: 'Search',
  searchPlaceholder: 'Key, text, field…',
  searchClear: 'Clear search',
  opFilterHint: 'Filter by operation',
  emptyAfterFilter: 'Nothing matches the current filter. Try clearing search or toggling operations.',
  showingFiltered: (visible: number, total: number) =>
    visible === total ? `${total} entries` : `${visible} of ${total} entries`,
  loadMore: 'Load more',
  loadingMore: 'Loading…',
  endOfHistory: 'End of history',
  compareCheckbox: 'Pick for compare',
  compareShort: 'Compare',
  compareSelected: (n: number) => `Selected: ${n}/2`,
  compareDifferentKeys: 'Only versions of the same key can be compared',
  compareAction: 'Compare selected',
  compareReset: 'Clear compare selection',
};

export type AdminContentHistoryContent = typeof ru;

const adminContentHistoryContentByLocale: Record<Locale, typeof ru> = { ru, en };

export const getAdminContentHistoryContent = (locale: Locale) => adminContentHistoryContentByLocale[locale];

export const adminContentHistoryContent = ru;
