export const adminBackgroundsPageContent = {
  title: 'Фоны',
  subtitle: 'Глобальный фон сайта',
  loadingSubtitle: 'Управление глобальным фоном сайта',
  saving: 'Сохранение...',
  backgroundPickerTitle: 'Выбор фона',
  settingsTitle: 'Настройки',
  resetButton: 'Сбросить',
  motionLabel: 'Скорость анимации',
  motionOptions: {
    slow: 'Медленно',
    normal: 'Нормально',
    fast: 'Быстро',
  },
  starBorderTitle: 'Star Border',
  starBorderSubtitle: 'Светящаяся рамка при наведении',
  starBorderOn: 'Вкл',
  starBorderOff: 'Выкл',
  starBorderEnable: 'Включить',
  starBorderDisable: 'Выключить',
  starBorderColor: 'Цвет',
  starBorderSpeed: 'Скорость',
  starBorderThickness: 'Толщина',
  starBorderGlow: 'Свечение',
} as const;
