export const adminPackagesPageContent = {
  validation: {
    idPositive: 'ID должен быть числом',
    nameRequired: 'Название обязательно',
    forFormatsRequired: 'Укажите хотя бы 1 формат',
    includesRequired: 'Укажите состав пакета',
  },
  toast: {
    saveError: 'Ошибка сохранения пакета',
    created: 'Пакет добавлен',
    updated: 'Пакет обновлён',
    deleted: 'Пакет удалён',
    deleteError: 'Ошибка удаления пакета',
    resetSuccess: 'Пакеты сброшены к дефолту',
  },
  layout: {
    title: 'Пакеты',
    subtitle: 'Управление пакетами и ценовыми предложениями',
  },
  deleteModal: {
    title: 'Удалить пакет?',
    confirmText: 'Удалить',
    cancelText: 'Отмена',
    description: (name: string) => `Пакет "${name}" будет удален без возможности восстановления.`,
  },
  resetModal: {
    title: 'Сбросить все пакеты к дефолту?',
    description: 'Текущие изменения будут перезаписаны демо-данными.',
    confirmText: 'Сбросить',
    cancelText: 'Отмена',
  },
  form: {
    editTitle: 'Редактирование пакета',
    createTitle: 'Новый пакет',
    editDescription: (id: number) =>
      `Вы редактируете пакет ${String(id)}. Сохраните изменения или нажмите «Отмена».`,
    createDescription: 'Создайте новый пакет или выберите существующий справа для редактирования.',
    restoredDraft: 'Восстановлен черновик формы, можно продолжить с того же места.',
    editMode: 'Режим редактирования',
    unsavedChanges: 'Есть несохраненные изменения',
    cancel: 'Отмена',
    idLabel: 'ID',
    nameLabel: 'Название',
    forFormatsLabel: 'Для форматов',
    forFormatsHint: 'Через запятую или новую строку',
    includesLabel: 'Состав',
    includesHint: 'Каждый пункт с новой строки',
    optionsLabel: 'Опции',
    optionsHint: 'Необязательно',
    priceHintLabel: 'Подсказка цены',
    save: 'Сохранить',
    add: 'Добавить',
  },
  list: {
    title: 'Список пакетов',
    shown: (filteredCount: number, totalCount: number) => `Показано ${filteredCount} из ${totalCount}`,
    resetToDefault: 'Сброс к дефолту',
    searchPlaceholder: 'Поиск по названию, ID, составу, опциям...',
    clear: 'Очистить',
    forFormatsPrefix: 'Для:',
    includesPrefix: 'Состав:',
    edit: 'Редактировать',
    remove: 'Удалить',
    emptyTitle: 'Пакетов пока нет',
    notFoundTitle: 'Ничего не найдено',
    emptyDescription: 'Добавьте первый пакет через форму слева.',
    notFoundDescription: 'Попробуйте изменить поисковый запрос или очистить фильтр.',
  },
} as const;
