export const adminLeadsContent = {
  layout: {
    title: 'Лента заявок',
    subtitle: 'Все заявки с сайта и подробный журнал их доставки',
  },
  statusLabels: {
    queued: 'В очереди',
    processing: 'В обработке',
    delivered: 'Доставлено',
    partial: 'Частично',
    failed: 'Ошибка',
    newFallback: 'Новый',
  },
  entryStatusLabels: {
    pending: 'Ожидает',
    success: 'Успешно',
    warning: 'Предупреждение',
    error: 'Ошибка',
  },
  channelLabels: {
    system: 'Система',
    api: 'API',
    telegram: 'Telegram',
    email: 'Email',
    'client-email': 'Письмо клиенту',
    database: 'База',
  },
  requestId: {
    label: 'Request ID',
  },
  logModal: {
    title: 'Лог заявки',
    close: 'Закрыть',
    cards: {
      status: 'Статус',
      created: 'Создана',
      steps: 'Шагов',
    },
    empty: 'Подробный лог еще не записан.',
  },
  leadCard: {
    actions: {
      log: 'Лог',
      page: 'Страница',
    },
    fields: {
      phone: 'Телефон',
      email: 'Email',
      telegram: 'Telegram',
      city: 'Город',
      date: 'Дата',
      format: 'Формат',
      lastStep: 'Последний шаг',
      details: 'Детали расчета',
      comment: 'Комментарий',
    },
  },
  confirm: {
    clearTitle: 'Очистить все заявки?',
    clearDescription: 'Будут удалены все записи из таблицы leads. Действие необратимо.',
    clearConfirm: 'Очистить',
    cancel: 'Отмена',
  },
  loading: {
    title: 'Загрузка заявок',
    description: 'Подождите, данные подтягиваются из базы',
  },
  errors: {
    prefix: 'Ошибка',
  },
  summary: {
    shown: (filtered: number, total: number) => `Показано: ${filtered} из ${total}`,
  },
  actions: {
    exportCsv: 'Экспорт CSV',
    exportJson: 'Экспорт JSON',
    clearAll: 'Очистить все',
  },
  chips: {
    search: (value: string) => `Поиск: ${value}`,
    source: (value: string) => `Источник: ${value}`,
    reset: 'Сбросить фильтры',
  },
  filters: {
    searchLabel: 'Поиск',
    searchPlaceholder: 'Имя, телефон, email, город, request id',
    sourceLabel: 'Источник',
    sourceAll: 'Все источники',
  },
  empty: {
    noLeadsTitle: 'Заявок пока нет',
    noLeadsDescription: 'После первой отправки формы здесь появятся карточки заявок и журнал доставки.',
    notFoundTitle: 'Ничего не найдено',
    notFoundDescription: 'Измените поисковый запрос или сбросьте фильтры.',
  },
  toasts: {
    clearSuccess: 'Заявки удалены',
    clearError: 'Не удалось удалить заявки',
    exportJsonSuccess: 'JSON экспорт готов',
    exportJsonError: 'Ошибка экспорта JSON',
    exportCsvSuccess: 'CSV экспорт готов',
    exportCsvError: 'Ошибка экспорта CSV',
  },
  csvHeaders: [
    'ID',
    'Request ID',
    'Дата',
    'Время',
    'Источник',
    'Статус',
    'Имя',
    'Телефон',
    'Email',
    'Telegram',
    'Город',
    'Дата события',
    'Формат',
    'Комментарий',
  ],
} as const;
