import type { Locale } from '../../i18n/types';

const ru = {
  layout: {
    title: 'Лента заявок',
    subtitle: 'Все заявки с сайта, источники, контакты и журнал доставки',
  },
  statusLabels: {
    queued: 'В очереди',
    processing: 'В обработке',
    delivered: 'Доставлено',
    partial: 'Частично',
    failed: 'Ошибка',
    newFallback: 'Новая',
  },
  entryStatusLabels: {
    pending: 'Ожидает',
    success: 'Успешно',
    warning: 'Предупреждение',
    error: 'Ошибка',
  },
  channelLabels: {
    system: 'Система',
    api: 'API',
    telegram: 'Telegram',
    email: 'Email',
    'client-email': 'Письмо клиенту',
    database: 'База',
  },
  requestId: {
    label: 'Request ID',
  },
  logModal: {
    title: 'Журнал доставки',
    close: 'Закрыть',
    cards: {
      status: 'Статус',
      created: 'Создана',
      steps: 'Шагов',
    },
    empty: 'Подробный лог пока не записан.',
  },
  detailsDrawer: {
    title: 'Карточка заявки',
    close: 'Закрыть',
    sections: {
      contacts: 'Контакты',
      origin: 'Источник',
      request: 'Запрос',
      extra: 'Дополнительные поля',
      delivery: 'Доставка',
    },
    fields: {
      created: 'Создана',
      pagePath: 'Страница',
      referrer: 'Переход',
    },
    actions: {
      openLog: 'Полный лог',
    },
  },
  leadCard: {
    actions: {
      log: 'Лог',
      page: 'Страница',
    },
    fields: {
      phone: 'Телефон',
      email: 'Email',
      telegram: 'Telegram',
      city: 'Город',
      date: 'Дата',
      format: 'Формат',
      lastStep: 'Последний шаг',
      details: 'Детали расчета',
      comment: 'Комментарий',
      noDetails: 'Без дополнительных деталей',
      noLog: 'Лог доставки пуст',
      noOrigin: 'Источник не указан',
      referrer: 'Переход',
      noContact: 'Контакт не указан',
    },
  },
  confirm: {
    clearTitle: 'Скрыть все заявки?',
    clearDescription: 'Все активные заявки будут скрыты из списка. Записи останутся в базе как архивные.',
    clearConfirm: 'Скрыть',
    cancel: 'Отмена',
  },
  deleteModal: {
    title: 'Скрыть заявку?',
    description: (name: string) => `Заявка «${name}» будет скрыта из активного списка.`,
    action: 'Скрыть',
    success: 'Заявка скрыта',
    error: 'Не удалось скрыть заявку',
  },
  loading: {
    title: 'Загружаем заявки',
    description: 'Данные подтягиваются из базы',
  },
  errors: {
    title: 'Не удалось загрузить заявки',
    prefix: 'Ошибка',
  },
  summary: {
    shown: (filtered: number, total: number) => `Показано: ${filtered} из ${total}`,
  },
  stats: {
    total: 'Всего заявок',
    today: 'Сегодня',
    todayHint: 'Новые обращения за день',
    sources: 'Источники',
    sourcesHint: 'Активные точки входа',
    contactRate: 'С контактами',
    contactRateHint: 'Есть email или Telegram',
    failedHint: (count: number) => `Ошибки доставки: ${count}`,
  },
  actions: {
    exportCsv: 'CSV',
    exportJson: 'JSON',
    markAllRead: 'Прочитать все',
    clearAll: 'Скрыть все',
  },
  toolbar: {
    title: 'Рабочий список',
    subtitle: 'Фильтруйте поток, выгружайте данные и открывайте журнал доставки.',
  },
  chips: {
    search: (value: string) => `Поиск: ${value}`,
    source: (value: string) => `Источник: ${value}`,
    reset: 'Сбросить фильтры',
  },
  filters: {
    searchLabel: 'Поиск',
    searchPlaceholder: 'Имя, телефон, email, город, request id',
    sourceLabel: 'Источник',
    sourceAll: 'Все источники',
  },
  quickPresets: {
    title: 'Быстрые фильтры',
    all: 'Все',
    unread: 'Непрочитанные',
    today: 'Сегодня',
    week: '7 дней',
    failed: 'С ошибкой',
  },
  bulk: {
    selected: (n: number) => `Выбрано: ${n}`,
    selectAllVisible: 'Выбрать все видимые',
    clear: 'Снять выделение',
    markRead: 'Отметить прочитанными',
    delete: 'Скрыть выбранные',
    confirmTitle: (n: number) => `Скрыть ${n} заявок?`,
    confirmDescription: 'Выбранные заявки будут скрыты из активного списка.',
    success: (n: number) => `Скрыто заявок: ${n}`,
    error: 'Не удалось скрыть часть заявок',
    markedRead: (n: number) => `Прочитано: ${n}`,
  },
  channelLabel: 'Канал',
  table: {
    client: 'Клиент',
    contacts: 'Контакты',
    origin: 'Источник',
    request: 'Запрос',
    delivery: 'Доставка',
    actions: 'Действия',
  },
  empty: {
    noLeadsTitle: 'Заявок пока нет',
    noLeadsDescription: 'После первой отправки формы здесь появятся заявки и журнал доставки.',
    notFoundTitle: 'Ничего не найдено',
    notFoundDescription: 'Измените поисковый запрос или сбросьте фильтры.',
  },
  toasts: {
    markAllReadSuccess: 'Все заявки прочитаны',
    markAllReadError: 'Не удалось отметить заявки',
    clearSuccess: 'Заявки скрыты',
    clearError: 'Не удалось скрыть заявки',
    exportJsonSuccess: 'JSON экспорт готов',
    exportJsonError: 'Ошибка экспорта JSON',
    exportCsvSuccess: 'CSV экспорт готов',
    exportCsvError: 'Ошибка экспорта CSV',
  },
  sourceLabels: {
    paths: {
      '/': 'Главная',
      '/services': 'Услуги',
      '/about': 'О нас',
      '/contacts': 'Контакты',
      '/cases': 'Кейсы',
      '/prices': 'Цены',
      '/rent': 'Аренда',
    },
    sources: {
      hero_form: 'Форма Hero',
      cta_form: 'CTA-форма',
      callback: 'Обратный звонок',
      footer_form: 'Футер',
      header_button: 'Хедер',
      consult_form: 'Консультация',
      'visual-led-config': 'Visual LED конфигуратор',
    },
    unknown: 'Не указано',
  },
  csvHeaders: [
    'ID',
    'Request ID',
    'Дата',
    'Время',
    'Источник',
    'Статус',
    'Имя',
    'Телефон',
    'Email',
    'Telegram',
    'Город',
    'Дата события',
    'Формат',
    'Комментарий',
  ],
};

const en: typeof ru = {
  layout: {
    title: 'Leads feed',
    subtitle: 'All website leads, sources, contacts, and delivery logs',
  },
  statusLabels: {
    queued: 'Queued',
    processing: 'Processing',
    delivered: 'Delivered',
    partial: 'Partial',
    failed: 'Failed',
    newFallback: 'New',
  },
  entryStatusLabels: {
    pending: 'Pending',
    success: 'Success',
    warning: 'Warning',
    error: 'Error',
  },
  channelLabels: {
    system: 'System',
    api: 'API',
    telegram: 'Telegram',
    email: 'Email',
    'client-email': 'Client email',
    database: 'Database',
  },
  requestId: {
    label: 'Request ID',
  },
  logModal: {
    title: 'Delivery log',
    close: 'Close',
    cards: {
      status: 'Status',
      created: 'Created',
      steps: 'Steps',
    },
    empty: 'Detailed log has not been recorded yet.',
  },
  detailsDrawer: {
    title: 'Lead card',
    close: 'Close',
    sections: {
      contacts: 'Contacts',
      origin: 'Origin',
      request: 'Request',
      extra: 'Extra fields',
      delivery: 'Delivery',
    },
    fields: {
      created: 'Created',
      pagePath: 'Page',
      referrer: 'Referrer',
    },
    actions: {
      openLog: 'Full log',
    },
  },
  leadCard: {
    actions: {
      log: 'Log',
      page: 'Page',
    },
    fields: {
      phone: 'Phone',
      email: 'Email',
      telegram: 'Telegram',
      city: 'City',
      date: 'Date',
      format: 'Format',
      lastStep: 'Last step',
      details: 'Estimate details',
      comment: 'Comment',
      noDetails: 'No extra details',
      noLog: 'Delivery log is empty',
      noOrigin: 'No origin',
      referrer: 'Referrer',
      noContact: 'No contact provided',
    },
  },
  confirm: {
    clearTitle: 'Hide all leads?',
    clearDescription: 'All active leads will be hidden from the list. Records will remain in the database as archived entries.',
    clearConfirm: 'Hide',
    cancel: 'Cancel',
  },
  deleteModal: {
    title: 'Hide lead?',
    description: (name: string) => `Lead "${name}" will be hidden from the active list.`,
    action: 'Hide',
    success: 'Lead hidden',
    error: 'Failed to hide lead',
  },
  loading: {
    title: 'Loading leads',
    description: 'Data is being fetched from the database',
  },
  errors: {
    title: 'Could not load leads',
    prefix: 'Error',
  },
  summary: {
    shown: (filtered: number, total: number) => `Shown: ${filtered} of ${total}`,
  },
  stats: {
    total: 'Total leads',
    today: 'Today',
    todayHint: 'New requests today',
    sources: 'Sources',
    sourcesHint: 'Active entry points',
    contactRate: 'With contacts',
    contactRateHint: 'Email or Telegram exists',
    failedHint: (count: number) => `Delivery errors: ${count}`,
  },
  actions: {
    exportCsv: 'CSV',
    exportJson: 'JSON',
    markAllRead: 'Mark all read',
    clearAll: 'Hide all',
  },
  toolbar: {
    title: 'Workspace',
    subtitle: 'Filter the flow, export data, and open delivery logs.',
  },
  chips: {
    search: (value: string) => `Search: ${value}`,
    source: (value: string) => `Source: ${value}`,
    reset: 'Reset filters',
  },
  filters: {
    searchLabel: 'Search',
    searchPlaceholder: 'Name, phone, email, city, request id',
    sourceLabel: 'Source',
    sourceAll: 'All sources',
  },
  quickPresets: {
    title: 'Quick filters',
    all: 'All',
    unread: 'Unread',
    today: 'Today',
    week: '7 days',
    failed: 'With error',
  },
  bulk: {
    selected: (n: number) => `Selected: ${n}`,
    selectAllVisible: 'Select all visible',
    clear: 'Clear selection',
    markRead: 'Mark as read',
    delete: 'Hide selected',
    confirmTitle: (n: number) => `Hide ${n} leads?`,
    confirmDescription: 'Selected leads will be hidden from the active list.',
    success: (n: number) => `Hidden: ${n}`,
    error: 'Failed to hide some leads',
    markedRead: (n: number) => `Marked read: ${n}`,
  },
  channelLabel: 'Channel',
  table: {
    client: 'Client',
    contacts: 'Contacts',
    origin: 'Origin',
    request: 'Request',
    delivery: 'Delivery',
    actions: 'Actions',
  },
  empty: {
    noLeadsTitle: 'No leads yet',
    noLeadsDescription: 'After the first form submission, lead cards and delivery logs will appear here.',
    notFoundTitle: 'Nothing found',
    notFoundDescription: 'Change your search query or reset filters.',
  },
  toasts: {
    markAllReadSuccess: 'All leads marked as read',
    markAllReadError: 'Failed to mark leads',
    clearSuccess: 'Leads hidden',
    clearError: 'Failed to hide leads',
    exportJsonSuccess: 'JSON export is ready',
    exportJsonError: 'JSON export failed',
    exportCsvSuccess: 'CSV export is ready',
    exportCsvError: 'CSV export failed',
  },
  sourceLabels: {
    paths: {
      '/': 'Home',
      '/services': 'Services',
      '/about': 'About',
      '/contacts': 'Contacts',
      '/cases': 'Cases',
      '/prices': 'Prices',
      '/rent': 'Rent',
    },
    sources: {
      hero_form: 'Hero form',
      cta_form: 'CTA form',
      callback: 'Callback',
      footer_form: 'Footer',
      header_button: 'Header',
      consult_form: 'Consult form',
      'visual-led-config': 'Visual LED configurator',
    },
    unknown: 'Unknown',
  },
  csvHeaders: [
    'ID',
    'Request ID',
    'Date',
    'Time',
    'Source',
    'Status',
    'Name',
    'Phone',
    'Email',
    'Telegram',
    'City',
    'Event date',
    'Format',
    'Comment',
  ],
};

const adminLeadsContentByLocale: Record<Locale, typeof ru> = { ru, en };

export const getAdminLeadsContent = (locale: Locale) => adminLeadsContentByLocale[locale];

export const adminLeadsContent = ru;
