export const backgroundContent = {
  starBorderLabels: {
    intensity: 'Интенсивность',
    color: 'Цвет рамки',
    speed: 'Скорость анимации (сек)',
    thickness: 'Толщина рамки',
    cornerOffset: 'Отступ старта от угла (px)',
  },
  commonLabels: {
    intensity: 'Интенсивность',
    contrast: 'Контраст',
    color1: 'Цвет 1',
    color2: 'Цвет 2',
    color3: 'Цвет 3',
    gridOpacity: 'Видимость сетки',
    rings: 'Количество колец',
    spread: 'Разброс',
    grain: 'Шум',
    hueShift: 'Сдвиг оттенка',
  },
  options: {
    theme: { name: 'По теме', description: 'Автовыбор по текущей теме сайта' },
    aurora: { name: 'Aurora', description: 'Мягкие переливы и сияние' },
    mesh: { name: 'Mesh Grid', description: 'Градиентная сетка в стиле React Bits' },
    dots: { name: 'Dot Matrix', description: 'Паттерн из точек с подсветкой' },
    waves: { name: 'Waves', description: 'Линейные волны и glow-слои' },
    rings: { name: 'Rings', description: 'Концентрические кольца и мягкий glow' },
    nebula: { name: 'Nebula', description: 'Туманность, зерно и цветовые сдвиги' },
    'color-bends': { name: 'Color Bends', description: 'Плавные жидкие переливы цвета' },
    'pixel-blast': { name: 'Pixel Blast', description: 'Пиксельный шум, рябь и glitch-настроение' },
    'line-waves': { name: 'Line Waves', description: 'Динамические волны из тонких линий' },
    galaxy: { name: 'Galaxy', description: 'Звёздное поле с глубиной и свечением' },
  },
} as const;
