export const mediaLibraryContent = {
  editModal: {
    title: 'Редактировать медиафайл',
    nameLabel: 'Название',
    tagsLabel: 'Теги (через запятую)',
    confirmText: 'Сохранить',
    cancelText: 'Отмена',
  },
  deleteModal: {
    title: 'Удалить файл?',
    description: (name: string) => `Файл "${name}" будет удален без возможности восстановления.`,
    confirmText: 'Удалить',
    cancelText: 'Отмена',
  },
  toolbar: {
    searchPlaceholder: 'Поиск по названию или тегам...',
    typeAll: 'Все',
    imagesOnlyTitle: 'Только изображения',
    videosOnlyTitle: 'Только видео',
    sortNewest: 'Новые сначала',
    sortOldest: 'Старые сначала',
    sortName: 'По названию',
    sortSize: 'По размеру',
    upload: 'Загрузить',
  },
  results: {
    loading: 'Загрузка...',
    found: (count: number) => `Найдено: ${count}`,
    totalTags: (count: number) => `Всего тегов: ${count}`,
  },
  empty: {
    title: 'Медиафайлы не найдены',
    filteredDescription: 'Попробуйте изменить параметры фильтра',
    initialDescription: 'Загрузите первые файлы, нажав кнопку выше',
  },
  list: {
    image: 'Изображение',
    video: 'Видео',
    separator: '•',
  },
  quickTags: {
    title: 'Быстрые категории',
    clear: 'Сбросить',
  },
  usage: {
    checking: 'Проверяю использование…',
    inUseSingular: (count: number) => `Используется в ${count} кейсе:`,
    inUsePlural: (count: number) =>
      count >= 5 ? `Используется в ${count} кейсах:` : `Используется в ${count} кейсах:`,
    notUsed: 'Файл не привязан к кейсам.',
    cascadeWarning: 'Связь с кейсом будет разорвана автоматически.',
  },
  details: {
    title: 'Детали файла',
    close: 'Закрыть',
    triggerTitle: 'Подробнее о файле',
    sections: {
      preview: 'Превью',
      meta: 'Свойства',
      usage: 'Где используется',
    },
    fields: {
      type: 'Тип',
      size: 'Размер',
      dimensions: 'Размеры',
      duration: 'Длительность',
      uploaded: 'Загружено',
      uploadedBy: 'Источник',
      tags: 'Теги',
      url: 'Storage path',
    },
    typeLabels: { image: 'Изображение', video: 'Видео' },
    usageLoading: 'Проверяю использование…',
    usageEmpty: 'Не используется ни в одном кейсе',
    usageItem: (title: string) => `Кейс: ${title}`,
    copyLink: 'Скопировать ссылку',
    openExternal: 'Открыть в новой вкладке',
    copySuccess: 'Ссылка скопирована',
    copyError: 'Не удалось скопировать',
  },
} as const;
