// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/Contrast.tsx": () => import("../components/mockups/homepage/Contrast.tsx"),
  "./components/mockups/homepage/Mosaic.tsx": () => import("../components/mockups/homepage/Mosaic.tsx"),
  "./components/mockups/homepage/Reportage.tsx": () => import("../components/mockups/homepage/Reportage.tsx")
};
