-- Seed about/led/support/rent bundled content into site_content for inline editing.
-- Mirrors src/content/pages/{about,led,support,rent}.ts.

INSERT INTO public.site_content (id, key, content, content_en, is_published)
VALUES (
  'page_about',
  'page_about',
  $ru${"seo":{"title":"О компании | Фьючер Скрин","description":"Фьючер Скрин — техсопровождение мероприятий с 2007 года. Инженеры, монтажные бригады, работа по всей РФ."},"section":{"title":"О компании","subtitle":"С 2007 года, технический партнёр для событий по всей РФ"},"paragraphs":["Мы работаем с 2007 года и сопровождаем форумы, концерты, выставки и презентации. В штате — инженеры, монтажные бригады и продюсеры, которые отвечают за результат на площадке.","География: Екатеринбург и регион, Москва/СПб, а также выезды по РФ. Согласовываем площадку, точки крепления, схемы питания и логистику.","Мы дорожим репутацией: закладываем резерв по запросу, прозрачно считаем сметы и держим сроки монтажа/демонтажа."],"factsTitle":"Факты","facts":["2007+ лет опыта","Проекты по РФ: форумы, городские события, выставки","Инженеры и монтажные бригады в штате","Резерв оборудования и процессинга по запросу"]}$ru$,
  $en${"seo":{"title":"About Company | Future Screen","description":"Future Screen provides technical event production since 2007. In-house engineers, installation crews, and nationwide operations."},"section":{"title":"About Company","subtitle":"Since 2007, your technical partner for events across Russia"},"paragraphs":["We have been working since 2007 and support forums, concerts, exhibitions, and presentations. Our in-house team includes engineers, installation crews, and producers responsible for on-site results.","Geography: Yekaterinburg and region, Moscow/Saint Petersburg, as well as projects across Russia. We align venue constraints, rigging points, power schemes, and logistics in advance.","We value reputation: add backup options on request, provide transparent estimates, and keep installation/dismantling timelines under control."],"factsTitle":"Facts","facts":["18+ years of experience","Projects across Russia: forums, city events, exhibitions","In-house engineers and installation crews","Equipment and processing backup on request"]}$en$,
  true
)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.site_content (id, key, content, content_en, is_published)
VALUES (
  'page_led',
  'page_led',
  $ru${"seo":{"title":"LED-экраны — аренда и монтаж | Фьючер Скрин","description":"Аренда LED-экранов для мероприятий: задники сцен, порталы, вогнутые конструкции. Монтаж, процессинг, инженеры."},"hero":{"title":"LED-экраны","subtitle":"Задники сцен, порталы, вогнутые и подвесные конструкции"},"benefitsTitle":"Преимущества","benefits":["Яркость и контраст при солнце и сценическом свете","Модульность: любые размеры и формы","Быстрая сборка/разборка, лёгкие корпуса","Процессинг, инженеры и сервис в комплекте"],"configsTitle":"Типовые конфигурации","configs":["Задник сцены с порталом и крыльями","Подвесная конструкция для помещений","Вогнутый/выпуклый экран с радиусом","Стойка/тотем для стоек регистрации","Порталы и подиумы для входных групп"],"selection":{"title":"Как выбрать","subtitle":"Простая логика под задачу","cards":[{"caption":"Шаг пикселя","title":"От расстояния до зрителя","description":"До 5 м — 2–2.6 мм, 5–10 м — 3–4 мм, улица/дальше — 4–6 мм."},{"caption":"Конструкция","title":"Зал, улица или подвес","description":"Подбираем рамы, подвес, стойки с учётом нагрузок и ветровых зон."},{"caption":"Содержание","title":"Плейаут и процессинг","description":"Медиасервер, коммутаторы, резервный источник по запросу."}]},"faqTitle":"FAQ","faq":["Как выбрать шаг пикселя? — От расстояния до зрителя: 2–3 мм для помещений, 3–4 мм для улицы.","Что входит? — Доставка, монтаж, процессинг, инженер на площадке (по договорённости).","Можно ли подвесить? — Да, при наличии точек крепления и расчёте нагрузок.","Есть ли резерв? — Можем заложить резервные модули и процессинг по запросу."],"included":{"title":"Что входит","items":["Доставка и монтаж","Процессинг и плейаут","Инженер на площадке","Резерв по запросу"]},"form":{"title":"Подобрать LED-решение","subtitle":"Опишите площадку и формат, подберём конфигурацию и КП.","ctaText":"Получить предложение"}}$ru$,
  $en${"seo":{"title":"LED Screens — Rental and Installation | Future Screen","description":"LED screen rental for events: stage backdrops, portals, and curved structures. Installation, processing, and engineering included."},"hero":{"title":"LED Screens","subtitle":"Stage backdrops, portals, curved and suspended structures"},"benefitsTitle":"Benefits","benefits":["High brightness and contrast in sunlight and stage lighting","Modularity: any size and shape","Fast setup and teardown with lightweight cabinets","Processing, engineers, and service included"],"configsTitle":"Typical Configurations","configs":["Stage backdrop with portal and side wings","Suspended construction for indoor venues","Concave/convex screen with radius setup","Stand/totem for registration desks","Portals and podiums for entrance groups"],"selection":{"title":"How to choose","subtitle":"A simple logic based on your task","cards":[{"caption":"Pixel pitch","title":"Based on viewing distance","description":"Up to 5 m — 2–2.6 mm, 5–10 m — 3–4 mm, outdoor/farther — 4–6 mm."},{"caption":"Construction","title":"Indoor, outdoor, or suspended","description":"We select frames, rigging, and stands based on loads and wind zones."},{"caption":"Content","title":"Playout and processing","description":"Media server, switchers, and optional backup source."}]},"faqTitle":"FAQ","faq":["How to choose pixel pitch? — Based on viewing distance: 2–3 mm indoors, 3–4 mm outdoors.","What is included? — Delivery, installation, processing, and on-site engineer (by agreement).","Can it be suspended? — Yes, with available rigging points and load calculation.","Do you provide backup? — Yes, we can include backup modules and processing on request."],"included":{"title":"What is included","items":["Delivery and installation","Processing and playout","On-site engineer","Backup on request"]},"form":{"title":"Select an LED setup","subtitle":"Describe venue and format, and we will prepare configuration and quote.","ctaText":"Get proposal"}}$en$,
  true
)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.site_content (id, key, content, content_en, is_published)
VALUES (
  'page_support',
  'page_support',
  $ru${"seo":{"title":"Техсопровождение мероприятий | Фьючер Скрин","description":"Пакеты техсопровождения мероприятий: LED, звук, свет, сцены. Лайт, Медиум, Биг — под любой формат."},"hero":{"title":"Техсопровождение под ключ","subtitle":"Лайт · Медиум · Биг — под формат мероприятия"},"loading":"Загрузка...","universalBadge":"Универсальный","optionsPrefix":"Опции:","formatsPrefix":"Для:","discussPackage":"Обсудить пакет","process":{"title":"Процесс","subtitle":"Прозрачно и с резервом","stepPrefix":"Шаг","items":["Бриф: что, где, когда, формат мероприятия","Расчёт и КП за 15 минут, схемы площадки","Подбор оборудования, резерв по запросу","Логистика, монтаж, программирование","Сопровождение инженерами, оперативные правки","Демонтаж и отчёт"]},"advantages":{"title":"Почему мы","items":["С 2007 года, проекты по всей РФ","Инженеры и монтажные бригады в штате","Резерв оборудования и процессинга по запросу","Отвечаем за результат и сроки"]},"form":{"title":"Получить предложение","subtitle":"Опишите формат — подберём пакет и состав","ctaText":"Запросить КП"}}$ru$,
  $en${"seo":{"title":"Event Technical Production | Future Screen","description":"Technical production packages for events: LED, sound, lighting, and stage. Lite, Medium, Big for any format."},"hero":{"title":"Turnkey Technical Production","subtitle":"Lite · Medium · Big — adjusted to your event format"},"loading":"Loading...","universalBadge":"Universal","optionsPrefix":"Options:","formatsPrefix":"For:","discussPackage":"Discuss package","process":{"title":"Process","subtitle":"Transparent and with backup","stepPrefix":"Step","items":["Brief: what, where, when, and event format","Estimate and proposal in 15 minutes, venue scheme","Equipment selection, backup on request","Logistics, setup, and programming","On-site engineering support and quick adjustments","Dismantling and reporting"]},"advantages":{"title":"Why us","items":["Since 2007, projects across Russia","In-house engineers and installation teams","Equipment and processing backup on request","Clear ownership of results and deadlines"]},"form":{"title":"Get a proposal","subtitle":"Describe the event format, and we will suggest package and scope","ctaText":"Request quote"}}$en$,
  true
)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.site_content (id, key, content, content_en, is_published)
VALUES (
  'page_rent',
  'page_rent',
  $ru${"seo":{"title":"Аренда оборудования для мероприятий | Фьючер Скрин","description":"Аренда светового, звукового, видеооборудования, сцен и инструментов для мероприятий."},"hero":{"title":"Аренда оборудования","subtitle":"Свет, звук, видео, сцены, инструменты","loading":"Загрузка...","error":"Ошибка загрузки категорий"},"checklist":{"title":"Что важно учесть","items":["Формат и площадка: зал/улица, высота потолка, точки подвеса","Сценарий: выступления, презентации, трансляция, количество микрофонов","Сроки и логистика: окна на монтаж/демонтаж, доступы","Резерв: источник питания, процессинг, запасные каналы"]},"form":{"title":"Запросить аренду","subtitle":"Опишите формат и площадку, подберём комплект","ctaText":"Получить подбор"}}$ru$,
  $en${"seo":{"title":"Event Equipment Rental | Future Screen","description":"Rental of lighting, audio, video equipment, stage structures, and instruments for events."},"hero":{"title":"Equipment Rental","subtitle":"Lighting, sound, video, stages, instruments","loading":"Loading...","error":"Failed to load categories"},"checklist":{"title":"What to consider","items":["Format and venue: indoor/outdoor, ceiling height, rigging points","Scenario: performances, presentations, broadcast, microphone count","Timeline and logistics: installation/dismantling windows, access","Backup: power source, processing, spare channels"]},"form":{"title":"Request rental","subtitle":"Describe event format and venue, and we will prepare a setup","ctaText":"Get selection"}}$en$,
  true
)
ON CONFLICT (key) DO NOTHING;

