-- Seed home.equipmentSection into site_content so inline edits upsert into
-- an existing row (the other home.* sections were seeded in
-- 20260422_seed_home_sections.sql — this one was the remaining gap).
--
-- Mirrors src/content/pages/home.ts (ru + en). ON CONFLICT DO NOTHING so
-- re-running the migration is a no-op if the row already exists (e.g.
-- admin clicked "initialize from static" before this migration shipped).

INSERT INTO public.site_content (id, key, content, content_en, is_published)
VALUES (
  'home_equipment_section',
  'home_equipment_section',
  $ru${"badge":"Парк оборудования","title":"Оборудование","accentTitle":"в аренду","subtitle":"Полный спектр профессионального оборудования для мероприятий любого масштаба","items":[{"iconKey":"led","title":"LED-экраны","desc":"Интерьерные и уличные светодиодные экраны различного размера и разрешения от 2.6мм шаг пикселя","bullets":["Экраны от 3×2м до 10×6м","Модульная система сборки","Фермовые конструкции до 7м"],"gradient":"linear-gradient(135deg, #667eea, #764ba2)","link":"/rent/video","photo":"/images/led-closeup.png"},{"iconKey":"panel","title":"Плазменные панели","desc":"LED и OLED панели диагональю от 32\" до 100\" для презентаций и выставок","bullets":["Диагонали 32\"—100\"","4K Ultra HD разрешение","Более 300 панелей в парке"],"gradient":"linear-gradient(135deg, #4facfe, #00f2fe)","link":"/rent/video","photo":"/images/equip-plasma.png"},{"iconKey":"sound","title":"Звуковое оборудование","desc":"Профессиональные звуковые комплекты, микрофоны, микшеры для концертов и конференций","bullets":["Активные акустические системы","Радиомикрофоны Shure/Sennheiser","Микшерные пульты"],"gradient":"linear-gradient(135deg, #f093fb, #f5576c)","link":"/rent/sound","photo":"/images/equip-sound.png"},{"iconKey":"light","title":"Световое оборудование","desc":"Прожекторы, PAR-ы, LED-панели, динамические головы для сценического освещения","bullets":["LED PAR и прожекторы","Динамические световые приборы","Контроллеры DMX"],"gradient":"linear-gradient(135deg, #ffd89b, #19547b)","link":"/rent/light","photo":"/images/equip-light.png"},{"iconKey":"stage","title":"Сценические конструкции","desc":"Модульные сцены, фермы, подиумы и трасты для создания площадок любой сложности","bullets":["Модульные сценические площадки","Алюминиевые фермы","Подвес для света и экранов"],"gradient":"linear-gradient(135deg, #11998e, #38ef7d)","link":"/rent/stage","photo":"/images/equip-stage.png"}],"extraItems":[{"iconKey":"computer","title":"Компьютеры и ноутбуки","desc":"Core i7/i5, игровые и офисные конфигурации","link":"/rent/computers","photo":"/images/equip-computers.png"},{"iconKey":"touch","title":"Тачскрины","desc":"Интерактивные столы 42\"–55\" с 10-точечным касанием","link":"/rent/touchscreens","photo":"/images/equip-touch.png"},{"iconKey":"staff","title":"Технический персонал","desc":"Видеооператоры, звукорежиссёры, техники","link":"/rent/staff","photo":"/images/equip-staff.png"}]}$ru$,
  $en${"badge":"Equipment fleet","title":"Equipment","accentTitle":"for rent","subtitle":"A full range of professional equipment for events of any scale","items":[{"iconKey":"led","title":"LED screens","desc":"Indoor and outdoor LED screens with different sizes and resolutions from 2.6 mm pixel pitch","bullets":["Screens from 3×2 m to 10×6 m","Modular assembly system","Truss structures up to 7 m"],"gradient":"linear-gradient(135deg, #667eea, #764ba2)","link":"/rent/video","photo":"/images/led-closeup.png"},{"iconKey":"panel","title":"Display panels","desc":"LED and OLED panels from 32\" to 100\" for presentations and exhibitions","bullets":["32\"—100\" diagonals","4K Ultra HD resolution","300+ panels in stock"],"gradient":"linear-gradient(135deg, #4facfe, #00f2fe)","link":"/rent/video","photo":"/images/equip-plasma.png"},{"iconKey":"sound","title":"Audio equipment","desc":"Professional PA systems, microphones, and mixers for concerts and conferences","bullets":["Active PA systems","Shure/Sennheiser wireless mics","Mixing consoles"],"gradient":"linear-gradient(135deg, #f093fb, #f5576c)","link":"/rent/sound","photo":"/images/equip-sound.png"},{"iconKey":"light","title":"Lighting equipment","desc":"Spotlights, PAR, LED panels, moving heads for stage lighting","bullets":["LED PAR and spotlights","Moving light fixtures","DMX controllers"],"gradient":"linear-gradient(135deg, #ffd89b, #19547b)","link":"/rent/light","photo":"/images/equip-light.png"},{"iconKey":"stage","title":"Stage structures","desc":"Modular stages, truss, podiums, and supports for complex venues","bullets":["Modular stage platforms","Aluminum truss","Suspension for light and screens"],"gradient":"linear-gradient(135deg, #11998e, #38ef7d)","link":"/rent/stage","photo":"/images/equip-stage.png"}],"extraItems":[{"iconKey":"computer","title":"Computers and laptops","desc":"Core i7/i5, gaming and office configurations","link":"/rent/computers","photo":"/images/equip-computers.png"},{"iconKey":"touch","title":"Touchscreens","desc":"42\"–55\" interactive displays with 10-point touch","link":"/rent/touchscreens","photo":"/images/equip-touch.png"},{"iconKey":"staff","title":"Technical crew","desc":"Video operators, sound engineers, and technicians","link":"/rent/staff","photo":"/images/equip-staff.png"}]}$en$,
  true
)
ON CONFLICT (key) DO NOTHING;
